### PR TITLE
Make dark scroll bar in dark theme

### PR DESCRIPTION
**Pull request by rakleed**
Make dark scroll bar in dark theme in Chromium-based browsers

### CODE REVIEW

**Comment by rakleed** [comment]
@MichaelDeBoey could you take a look please?

**Comment by MichaelDeBoey** [comment]
@rakleed Could you please rebase your branch onto latest `main` and resolve conflicts?

**Comment by rakleed** [comment]
@MichaelDeBoey done.

**Comment by MichaelDeBoey** [comment]
@rakleed It seems something went wrong while rebasing
Could you run the following command?
```
git checkout patch-1 && git fetch -p && git pull && git rebase main && git push -f
```

**Comment by rakleed** [comment]
@MichaelDeBoey done, it looks like everything is correct now.

**Review by MichaelDeBoey — APPROVED** [review]

**Pull request merged**
